
version: '3'

services:

  web:
#    image: tiangolo/uwsgi-nginx-flask:python3.7
    build: .
    image: mikkohei13/loxia
    container_name: loxia_web
    volumes:
      - ./app:/app
      - ./_source_audio:/_source_audio
      - ./_exports:/_exports
      - ./_temp:/_temp
    ports:
      - 80:80
    # networks:
    #   - loxia_net
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"

  mongodb:
    image: mongo:3.6
    container_name: loxia_mongodb
    restart: always
#    hostname: mongodb
    # networks:
    #   - loxia_net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-volume:/data/db

  mongo-express:
    image: mongo-express:0.49
    container_name: loxia_mongo-express
    restart: always
    depends_on: 
      - 'mongodb'
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb

  files:  
    image: nginx:1.17
    container_name: loxia_files
    volumes:
      - ./_exports:/usr/share/nginx/html:ro
    ports:
      - 8080:80

volumes: 
  mongodb-volume:
